### ISSUE TITLE
Invoking the plugin from a declarative pipeline script

### ISSUE THREAD

**Issue by cspang1** [kinow/tap-plugin#4]
We're using a declarative pipeline script to execute our build, and I'm unsure of how to invoke this plugin to gather and publish the tests.

From the documentation, it appears `ant` is required for invocation but goes no further, and says nothing about "publishing" the results themselves.

Thank you!

**Comment by kinow** [comment]
Hi @cspang1 , I haven't really used the plugin in declarative pipeline scripts, only freestyle ones. Will have a look next development cycle, but maybe pinging the users mailing list someone else will know how to use it.

**Comment by cspang1** [comment]
@kinow Thanks for the quick response! I was actually able to figure it out:

It's as simple as using 

```
step([$class: 'TapPublisher', testResults: '**/*.tap'])
```

in a scripted pipeline, and wrap it in ` script { } ` in a declarative pipeline. Some additional options:

```
step([$class: 'TapPublisher', discardOldReports: false, enableSubtests: false, failIfNoResults: false, 
    failedTestsMarkBuildAsFailure: true, flattenTapResult: false, includeCommentDiagnostics: false, 
    outputTapToConsole: true, planRequired: true, showOnlyFailures: false, skipIfBuildNotOk: false, 
    stripSingleParents: false, testResults: '**/*.tap', todoIsFailure: false, validateNumberOfTests: true, 
    verbose: true])
```
